blank_issues_enabled: false
contact_links:
  - name: Ory Label Sync Action Forum
    url: https://github.com/ory/label-sync-action/discussions
    about:
      Please ask and answer questions here, show your implementations and
      discuss ideas.
  - name: Ory Chat
    url: https://www.ory.sh/chat
    about:
      Hang out with other Ory community members to ask and answer questions.
